---
- name: create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: admin
      password: my_password
      instance: dev99999
      data:
        priority: 2
        short_description: "This is a test opened by Ansible"
    register: new_incident

  - debug: var=new_incident.record
