---
# tasks file for SNOW

- name: Create an incident
  snow_record:
    username: "{{ username }}"
    password: "{{ password }}'
    instance: "{{ instance }}"
    state: present
    data:
      short_description: "This is a test incident opened by Ansible"
      severity: 3
      priority: 2
  register: new_incident
