---
# tasks file for SNOW

- name: Create a change request
  snow_record:
    username: admin
    password: my_password
    instance: dev99999
    state: present
    data:
      short_description: "This is a test opened by Ansible"
      severity: 3
      priority: 2
    table: change_request
  register: new_change_request


- debug: var=new_change_request
